[project]
name = "utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Henry Williams", email = "henrywilliams95000@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
utils = "utils:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
